# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Rev:r)
stages: 
- stage: setup
  displayName: 'Pre-Build'
  jobs:
  - job: pre_build_checks
    displayName: 'Pre-Build Checks'  
    pool: default
    steps:
    - script: set
      displayName: 'Examine environment'

    - script: |
        echo running pre-build checks...
      displayName: 'Run pre-build checks'

- stage: build_windows
  displayName: 'Build Windows'
  dependsOn: setup
  jobs:
  - job: build
    displayName: 'Build'
    pool: default
    steps:
    - script: echo building...
      displayName: 'Build'
  - job: unit_test
    displayName: 'Unit Tests'
    dependsOn: build
    pool: default
    steps:
    - script: echo running unit tests...
      displayName: 'Unit Tests'

- stage: build_mac
  displayName: 'Build Mac'
  dependsOn: setup
  jobs:
  - job: build
    displayName: 'Build'
    pool: default
    steps:
    - script: set
      displayName: 'Examine environment'
    - script: echo building...
      displayName: 'Build'
  - job: unit_test
    displayName: 'Unit Tests'
    dependsOn: build
    pool: default
    steps:
    - script: |
        echo running unit tests...
        echo ##vso[task.logissue type=error;]error encountered
        exit 1
      continueOnError: true
      displayName: 'Unit Tests'

- stage: build_linux
  displayName: 'Build Linux'
  dependsOn: setup
  jobs:
  - job: build
    displayName: 'Build'
    pool: default
    steps:
    - script: echo building...
      displayName: 'Build'
    - script: |
        echo ##vso[task.logissue type=error;]error encountered
        exit 1
      displayName: 'fail now'
  - job: unit_test
    displayName: 'Unit Tests'
    dependsOn: build
    pool: default
    steps:
    - script: echo running unit tests...
      displayName: 'Unit Tests'

- stage: Deploy
  dependsOn: [build_windows, build_mac, build_linux]
  jobs:
  - job: deployment 
    displayName: 'Deployment'
    pool: default
    steps:
    - script: echo deploying...
      displayName: 'Deploy to production'
